### ISSUE TITLE
Error after update to Atom 1.19

### ISSUE THREAD

**Issue by ocssor** [atuttle/atom-language-cfml#106]
1. Update to Atom 1.19
2. Opened a CF File...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [language-cfml](https://github.com/atuttle/atom-language-cfml) package 0.17.0

### Stack Trace

Failed to activate the language-cfml package

```
At Cannot read property 'Symbol(Symbol.iterator)' of undefined

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at checkCfscriptEditorGrammar (/packages/language-cfml/lib/languageCFML.js:70:38)
    at /packages/language-cfml/lib/languageCFML.js:30:6
    at Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:717:15)
    at Object.activate (/packages/language-cfml/lib/languageCFML.js:24:42)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-bootstrap3 1.2.12 
atom-html-preview 0.1.22 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-wrap-in-tag 0.6.0 
gloom 0.6.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
language-cfml 0.17.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
northem-atom-syntax 2.1.0 
northem-atom-ui 2.1.0 
northem-dark-atom-syntax 2.1.0 
northem-dark-atom-ui 2.1.0 
northem-light-atom-syntax 2.1.0 
northem-light-atom-ui 2.1.1 
platformio-ide-terminal 2.5.5 
project-manager 3.3.5 
Sublime-Style-Column-Selection 1.7.4 
synced-sidebar 0.4.3 
```

**Comment by seancorfield** [comment]
See #105 for the fix.

**Comment by atuttle** [comment]
New version 0.17.1 pushed with #105 included

**Comment by ocssor** [comment]
Thanks guys!
