### ISSUE TITLE
Starting Atom: Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by icimasa** [atuttle/atom-language-cfml#85]
I get this error everytime I start Atom if there is a tab open with cfm files (CFML/HTML) language in the list that Atom wants to reopen, if there is not a tab open when starting Atom, everything is fine.. 

This issue has been since v. 1.7.0

I run Windows 10

C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\underscore-plus\node_modules\underscore\underscore.js:219

RangeError: Maximum call stack size exceeded
 at Array.indexOf (native)
 at Object..contains..include (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\underscore-plus\node_modules\underscore\underscore.js:219:68)
 at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar.js:275:14)
 at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
 at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
 at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
 at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
 at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
 at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
 at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
 at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
 at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
 at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
 at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
 at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
 at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
 at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
 at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
 at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
 at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
 at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
 at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
 at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
 at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
 at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
 at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
 at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
 at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
 at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
 at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
 at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\masa\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)

**Comment by mikoMK** [comment]
Can confirm this for Windows 8.1 and Atom 1.7.3, **but** only when Atom has to reopen files on a network drive. Local cfm files reopen without a problem.

**Comment by icimasa** [comment]
Hi, did confirm that too, all of my work is on network drive, and the error is still in 1.7.3!
I wonder if this is a bug in the cfml/html language pack or atom itself!

**Comment by atuttle** [comment]
That part of easy enough to test: disable the plugin and try again.

**Comment by icimasa** [comment]
@atuttle well sort of already confirmed that the error must be in the plugin, I just set the language on the files to regular text file and restarted atom without the error and then switched back to cfml/html and restarted and the error came back! So yea must be the cfml/html plugin! :)

**Comment by mikoMK** [comment]
Sorry, I forgot to mention that above: The error doesn't occure when "language-cfml" is disabled.
The error seems to cause no further problems. The cfm/cfc Files are completely loaded and you can still edit and save them and open other files without getting an error again.

**Comment by icimasa** [comment]
Yes correct everything works fine except that every time you start Atom, you get this error popup! So any new on fixing this?

**Comment by jcush** [comment]
I'm also getting this error (Win 8.1). Quite frustrating as it completely locks Atom up for a good 10 seconds. Any news on a fix?

**Comment by dannyrich** [comment]
It seems that this is related to the decisions in https://github.com/atuttle/atom-language-cfml/pull/35. If you force it to use cfml.cson rather than html-cfml.cson this error goes away and it loads quicker, but you lose html syntax highlighting if you do this.

**Comment by icimasa** [comment]
Ohh okay,,

Seems like relly sad if you cannot have cfml and html at the same time. So for me it is not an option, I solved it by forcing atom to allways open empty and I have to open up app pages from scratch.. ☹

Hope that this will be solved sometimes..

//Martin

**Comment by David-Polehonski** [comment]
Is this still an Issue?

**Comment by jcush** [comment]
For one I use VSCode now so I can't comment on if this is still an issue, sorry.

I don't know how Atom plugins are built, but looking at the above if there's some way to 'import' syntax highlighting rules then maybe that could be done in some way so you stick on cfml.cson for the quick, bug-free loading but still inherit html highlighting rules?

**Comment by David-Polehonski** [comment]
I don't experience this issue when loading atom with a file already loaded. So unless someone else thinks otherwise it may be worth closing this down for now?

**Comment by icimasa** [comment]
I haven't seen this error for a while now, but could also be that I changed how I work, when I open atom I always open it empty cause I work in so many different projects it was no point in opening up the last project with all tabs open..
